- name: Check for existing kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: kubeadm join
  command: "{{ hostvars[groups.master[0]]['joincommand'] }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: kubelet_conf.stat.exists == False

# For some reason "kubeadm join" does not write the correct value here
- name: HACK - replace --network-plugin=cni with --network-plugin=kubenet
  replace:
    path: /var/lib/kubelet/kubeadm-flags.env
    regexp: network-plugin=cni
    replace: "network-plugin=kubenet"