- name: install helm
  shell: "curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash"
  args:
    warn: no

- name: add repos to helm
  ignore_errors: yes
  command: helm repo add {{ item }}
  when: helm_repos | length > 0

- name: update the helm repos
  command: helm repo update

- name: install helm charts
  ignore_errors: yes
  command: helm install {{ item }}
  register: result
  retries: 30
  delay: 2
  until: result.rc == 0
  when: helm_install | length > 0
